apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-messaging-app
  template:
    metadata:
      labels:
        app: django-messaging-app
    spec:
      containers:
      - name: django-messaging-app
        image: chrismacharia/django-messaging-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: secret_key
        - name: DJANGO_DB_HOST
          value: localhost
        - name: DJANGO_DB_NAME
          value: messaging_app_db
        - name: DJANGO_DB_USER
          value: chris
        - name: DJANGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-db-credentials
              key: db_password

---
apiVersion: v1
kind: Service
metadata:
  name: django-messaging-app-service
spec:
  selector:
    app: django-messaging-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  clusterIP: None
